
document.addEventListener("DOMContentLoaded", function() {
  // Array de versículos e referências
const verses = [
      { verse: "Tudo posso naquele que me fortalece.", reference: "Filipenses 4:13" },
  { verse: "O Senhor é meu pastor e nada me faltará.", reference: "Salmos 23:1" },
  { verse: "Eu sou o caminho, a verdade, e a vida. E ninguém vem ao Pai senão por mim.", reference: "João 14:6" },
  { verse: "No mundo tereis aflições, mas tende bom ânimo, eu venci o mundo.", reference: "João 16:33" },
  { verse: "Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna.", reference: "João 3:16" },
  { verse: "Lâmpada para os meus pés é tua palavra, e luz para o meu caminho.", reference: "Salmos 119:105" },
  { verse: "Mas buscai primeiro o reino de Deus, e a sua justiça, e todas essas coisas vos serão acrescentadas.", reference: "Mateus 6:33" },
  { verse: "Entrega o teu caminho ao Senhor; confia nele, e ele o fará.", reference: "Salmos 37:5" },
  { verse: "Deleita-te também no Senhor, e te concederá os desejos do teu coração.", reference: "Salmos 37:4" },
  { verse: "O Senhor é a minha luz e a minha salvação; a quem temerei? O Senhor é a força da minha vida; de quem me recearei?", reference: "Salmos 27:1" },
  { verse: "Clama a mim, e responder-te-ei, e anunciar-te-ei coisas grandes e firmes que não sabes.", reference: "Jeremias 33:3" },
  { verse: "Pois eu bem sei os planos que estou planejando para vós, diz o Senhor; planos de paz e não de mal, para vos dar um futuro e uma esperança.", reference: "Jeremias 29:11" },
  { verse: "E sabemos que todas as coisas contribuem juntamente para o bem daqueles que amam a Deus, daqueles que são chamados segundo o seu propósito.", reference: "Romanos 8:28" },
  { verse: "Alegrai-vos na esperança, sede pacientes na tribulação, perseverai na oração.", reference: "Romanos 12:12" },
  { verse: "Mas Deus prova o seu amor para conosco, em que Cristo morreu por nós, sendo nós ainda pecadores.", reference: "Romanos 5:8" },
  { verse: "Porque a palavra de Deus é viva e eficaz, e mais cortante do que qualquer espada de dois gumes, e penetra até ao ponto de dividir alma e espírito, juntas e medulas, e é apta para discernir os pensamentos e intenções do coração.", reference: "Hebreus 4:12" },
  { verse: "Sem fé é impossível agradar a Deus, pois quem dele se aproxima precisa crer que ele existe e que recompensa aqueles que o buscam.", reference: "Hebreus 11:6" },
  { verse: "Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados, e nos purificar de toda a injustiça.", reference: "1 João 1:9" },
  { verse: "Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará.", reference: "Salmos 91:1" },
  { verse: "Bem-aventurados os que têm fome e sede de justiça, porque eles serão fartos.", reference: "Mateus 5:6" },
  { verse: "Bem-aventurados os pacificadores, porque eles serão chamados filhos de Deus.", reference: "Mateus 5:9" },
  { verse: "Respondeu Jesus: 'Está escrito: Nem só de pão viverá o homem, mas de toda palavra que procede da boca de Deus.'", reference: "Mateus 4:4" },
  { verse: "O ladrão não vem senão para roubar, matar e destruir; eu vim para que tenham vida, e a tenham com abundância.", reference: "João 10:10" },
  { verse: "Tudo que pedirdes em oração, crendo, recebereis.", reference: "Mateus 21:22" },
  { verse: "O Senhor, teu Deus, está no meio de ti, poderoso para te salvar; ele se deleitará em ti com alegria, renovar-te-á com o seu amor, regozijar-se-á em ti com brados de júbilo.", reference: "Sofonias 3:17" },
  { verse: "Confia no Senhor de todo o teu coração, e não te estribes no teu próprio entendimento. Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas.", reference: "Provérbios 3:5-6" },
  { verse: "Mas o fruto do Espírito é amor, alegria, paz, longanimidade, benignidade, bondade, fidelidade, mansidão, domínio próprio.", reference: "Gálatas 5:22-23" },
  { verse: "Ora, a fé é a certeza daquilo que esperamos e a prova das coisas que não vemos.", reference: "Hebreus 11:1" },
  { verse: "Tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor, e não aos homens.", reference: "Colossenses 3:23" },
  { verse: "Mas em todas estas coisas somos mais que vencedores, por aquele que nos amou.", reference: "Romanos 8:37" },
  { verse: "E o meu Deus, segundo a sua riqueza em glória, há de suprir em Cristo Jesus cada uma de vossas necessidades.", reference: "Filipenses 4:19" },
  { verse: "Bendito o homem que confia no Senhor, e cuja esperança é o Senhor.", reference: "Jeremias 17:7" },
  { verse: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia.", reference: "Salmos 46:1" },
  { verse: "Aquietai-vos, e sabei que eu sou Deus; sou exaltado entre as nações, sou exaltado na terra.", reference: "Salmos 46:10" },
  { verse: "Lancem sobre ele toda a sua ansiedade, porque ele tem cuidado de vocês.", reference: "1 Pedro 5:7" },
  { verse: "Se Deus é por nós, quem será contra nós?", reference: "Romanos 8:31" },
  { verse: "O amor é paciente, o amor é bondoso. Não inveja, não se vangloria, não se orgulha.", reference: "1 Coríntios 13:4" },
  { verse: "Pois o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna em Cristo Jesus, nosso Senhor.", reference: "Romanos 6:23" },
  { verse: "Eu sou a videira; vocês são os ramos. Se alguém permanecer em mim e eu nele, esse dará muito fruto; pois sem mim vocês não podem fazer coisa alguma.", reference: "João 15:5" },
  { verse: "Busquem o Senhor enquanto é possível achá-lo; clamem por ele enquanto está perto.", reference: "Isaías 55:6" },
  { verse: "Não fui eu que lhe ordenei? Seja forte e corajoso! Não se apavore nem desanime, pois o Senhor, o seu Deus, estará com você por onde você andar.", reference: "Josué 1:9" },
  { verse: "Ensina-nos a contar os nossos dias para que o nosso coração alcance sabedoria.", reference: "Salmos 90:12" },
  { verse: "O Senhor te guardará de todo mal; ele guardará a tua vida.", reference: "Salmos 121:7" },
  { verse: "Como é feliz aquele cujo auxílio é o Deus de Jacó, cuja esperança está no Senhor, no seu Deus.", reference: "Salmos 146:5" },
  { verse: "Eu pedi ao Senhor e ele me respondeu; livrou-me de todos os meus temores.", reference: "Salmos 34:4" },
  { verse: "Quem habita no abrigo do Altíssimo e descansa à sombra do Todo-poderoso pode dizer ao Senhor: Tu és o meu refúgio e a minha fortaleza, o meu Deus, em quem confio.", reference: "Salmos 91:1-2" },
  { verse: "Os que confiam no Senhor serão como o monte de Sião, que não se abala, mas permanece para sempre.", reference: "Salmos 125:1" },
  { verse: "O Senhor é bom, uma fortaleza no dia da angústia, e conhece os que nele confiam.", reference: "Naum 1:7" },
  { verse: "Esforçai-vos, e ele fortalecerá o vosso coração, vós todos que esperais no Senhor.", reference: "Salmos 31:24" },
  { verse: "Elevo os meus olhos para os montes; de onde vem o meu socorro? O meu socorro vem do Senhor, que fez os céus e a terra.", reference: "Salmos 121:1-2" },
  { verse: "Confia no Senhor para sempre, pois o Senhor Deus é uma rocha eterna.", reference: "Isaías 26:4" },
  { verse: "Venham a mim, todos os que estão cansados e sobrecarregados, e eu darei descanso a vocês.", reference: "Mateus 11:28" },
  { verse: "Ele te cobrirá com as suas penas, e debaixo das suas asas estarás seguro; a sua verdade será o teu escudo e broquel.", reference: "Salmos 91:4" },
  { verse: "E o Senhor te guiará continuamente, fartará a tua alma em lugares secos, e fortificará os teus ossos; serás como um jardim regado, e como um manancial cujas águas nunca faltam.", reference: "Isaías 58:11" },
  { verse: "O Senhor é bom para com aqueles cuja esperança está nele, para com aqueles que o buscam.", reference: "Lamentações 3:25" },
  { verse: "O Senhor te abençoe e te guarde; o Senhor faça resplandecer o seu rosto sobre ti e tenha misericórdia de ti; o Senhor sobre ti levante o seu rosto e te dê a paz.", reference: "Números 6:24-26" },
  { verse: "O Senhor é a minha rocha, a minha fortaleza e o meu libertador; o meu Deus é o meu rochedo, em quem me refugio. Ele é o meu escudo e o poder que me salva, a minha torre alta.", reference: "Salmos 18:2" },
  { verse: "Se alguém tem sede, venha a mim e beba. Quem crer em mim, como diz a Escritura, do seu interior correrão rios de água viva.", reference: "João 7:37-38" },
  { verse: "Assim que, se alguém está em Cristo, nova criatura é: as coisas velhas já passaram; eis que tudo se fez novo.", reference: "2 Coríntios 5:17" },
  { verse: "Eis que estou à porta e bato; se alguém ouvir a minha voz e abrir a porta, entrarei em sua casa e com ele cearei, e ele comigo.", reference: "Apocalipse 3:20" },
  { verse: "Não se turbe o vosso coração; credes em Deus, crede também em mim.", reference: "João 14:1" },
  { verse: "Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus; eu te fortaleço, e te ajudo, e te sustento com a destra da minha justiça.", reference: "Isaías 41:10" },
  { verse: "Confessai, pois, os vossos pecados uns aos outros, e orai uns pelos outros, para serdes curados. A oração de um justo é poderosa e eficaz.", reference: "Tiago 5:16" },
  { verse: "Porque sou eu que conheço os planos que tenho para vocês, diz o Senhor, planos de fazê-los prosperar e não de causar dano, planos de dar a vocês esperança e um futuro.", reference: "Jeremias 29:11" },
  { verse: "E a paz de Deus, que excede todo o entendimento, guardará os vossos corações e as vossas mentes em Cristo Jesus.", reference: "Filipenses 4:7" },
  { verse: "Portanto, se alguém está em Cristo, nova criatura é: as coisas velhas já passaram; eis que tudo se fez novo.", reference: "2 Coríntios 5:17" },
  { verse: "Porque o Filho do homem veio buscar e salvar o que se havia perdido.", reference: "Lucas 19:10" },
  { verse: "E Jesus, olhando para eles, disse: Para os homens é impossível, mas não para Deus, porque para Deus todas as coisas são possíveis.", reference: "Marcos 10:27" },
  { verse: "Disse-lhe Jesus: Eu sou a ressurreição e a vida; quem crê em mim, ainda que esteja morto, viverá;", reference: "João 11:25" },
  { verse: "Porque o Senhor corrige o que ama, e açoita a qualquer que recebe por filho.", reference: "Hebreus 12:6" },
  { verse: "Eu sou o bom pastor; o bom pastor dá a sua vida pelas ovelhas.", reference: "João 10:11" },
  { verse: "Não estejais inquietos por coisa alguma; antes as vossas petições sejam em tudo conhecidas diante de Deus pela oração e súplica com ação de graças.", reference: "Filipenses 4:6" },
  { verse: "Não andeis ansiosos por coisa alguma, mas em tudo, pela oração e súplica, e com ação de graças, apresentem os seus pedidos a Deus.", reference: "Filipenses 4:6" },
  { verse: "Em verdade, em verdade vos digo que quem ouve a minha palavra e crê naquele que me enviou, tem a vida eterna, e não entrará em condenação, mas passou da morte para a vida.", reference: "João 5:24" },
  { verse: "Bem-aventurados os humildes de espírito, porque deles é o reino dos céus.", reference: "Mateus 5:3" },
  { verse: "Porque onde estiver o vosso tesouro, aí estará também o vosso coração.", reference: "Mateus 6:21" },
  { verse: "Aquele que tem o Filho tem a vida; aquele que não tem o Filho de Deus não tem a vida.", reference: "1 João 5:12" },
  { verse: "E o Senhor, que é fiel, vos fortalecerá e vos guardará do maligno.", reference: "2 Tessalonicenses 3:3" },
  { verse: "Mas, como está escrito: As coisas que o olho não viu, e o ouvido não ouviu, e não subiram ao coração do homem, são as que Deus preparou para os que o amam.", reference: "1 Coríntios 2:9" },
  { verse: "Porque nele foram criadas todas as coisas que há nos céus e na terra, visíveis e invisíveis, sejam tronos, sejam dominações, sejam principados, sejam potestades; tudo foi criado por ele e para ele.", reference: "Colossenses 1:16" },
  { verse: "E, quando orardes, não sereis como os hipócritas; porque eles gostam de orar em pé nas sinagogas e nas esquinas das ruas, para serem vistos pelos homens. Em verdade vos digo que eles já receberam a sua recompensa.", reference: "Mateus 6:5" },
  { verse: "Pois eu sou o Senhor, o Deus de toda a humanidade. Há alguma coisa difícil demais para mim?", reference: "Jeremias 32:27" },
  { verse: "Porque, quanto ao Senhor, seus olhos passam por toda a terra, para mostrar-se forte para com aqueles cujo coração é totalmente dele.", reference: "2 Crônicas 16:9" },
  { verse: "Sede uns para com os outros benignos, misericordiosos, perdoando-vos uns aos outros, como também Deus vos perdoou em Cristo.", reference: "Efésios 4:32" },
  { verse: "Bem-aventurados os que choram, porque eles serão consolados.", reference: "Mateus 5:4" },
  { verse: "E já está próximo o fim de todas as coisas; portanto, sede sóbrios e vigiai em oração.", reference: "1 Pedro 4:7" },
  { verse: "Portanto, ide, ensinai todas as nações, batizando-as em nome do Pai, e do Filho, e do Espírito Santo;", reference: "Mateus 28:19" },
  { verse: "Assim, a fé vem pelo ouvir, e o ouvir pela palavra de Deus.", reference: "Romanos 10:17" },
  { verse: "Bem-aventurados os limpos de coração, porque eles verão a Deus.", reference: "Mateus 5:8" }

];
  // Seleciona um versículo aleatório
  const randomIndex = Math.floor(Math.random() * verses.length);
  const randomVerse = verses[randomIndex];
    const randomIndex2 = Math.floor(Math.random() * 16);

  // Atualiza o conteúdo dos elementos HTML
  document.getElementById("verse").textContent = randomVerse.verse;
  document.getElementById("reference").textContent = randomVerse.reference;
    document.getElementById("random-image-file").setAttribute("src", `${randomIndex2}.png`);
    console.log(document.getElementById("random-image-file").getAttribute("src"))
});
